# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
# Enables Gradle Build Cache.
org.gradle.caching=true
# Enables Gradle Configuration Cache, the preferred Gradle execution mode.
org.gradle.configuration-cache=true
# Run in incubating parallel mode.
org.gradle.parallel=true
# AndroidX package structure.
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete".
kotlin.code.style=official
# Each library's R class includes only the resources declared in the library itself.
android.nonTransitiveRClass=true
